Perform the following operations using Python on Hepatitis Dataset.  
a. Create data subsets for different sex.  
b. Merge two subsets  
c. Sort Data using age, SGOT, PROTIME.  
d. Transposing Data  
e. Melting Data to long format  
f. Casting data to wide format

In [12]:
import pandas as pd
import numpy as np

# Load the dataset
df = pd.read_csv(r"C:\Users\waghb\OneDrive\Desktop\dsbdal\DSBDALExam DataSets\Hepatitis\hepatitis_csv.csv")

In [13]:
df.head(5)

,age,sex,steroid,antivirals,fatigue,malaise,anorexia,liver_big,liver_firm,spleen_palpable,spiders,ascites,varices,bilirubin,alk_phosphate,sgot,albumin,protime,histology,class
0,30,male,False,False,False,False,False,False,False,False,False,False,False,1.0,85.0,18.0,4.0,NaN,False,live
1,50,female,False,False,True,False,False,False,False,False,False,False,False,0.9,135.0,42.0,3.5,NaN,False,live
2,78,female,True,False,True,False,False,True,False,False,False,False,False,0.7,96.0,32.0,4.0,NaN,False,live
3,31,female,NaN,True,False,False,False,True,False,False,False,False,False,0.7,46.0,52.0,4.0,80.0,False,live
4,34,female,True,False,False,False,False,True,False,False,False,False,False,1.0,NaN,200.0,4.0,NaN,False,live

In [14]:


# Replace '?' with NaN for proper handling
df.replace('?', np.nan, inplace=True)

# Convert relevant columns to numeric
numeric_cols = ['age', 'bilirubin', 'alk_phosphate', 'sgot', 'albumin', 'protime']
for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

# a. Create data subsets for different sex (1: male, 2: female)
male_subset = df[df['sex'] == 1]
female_subset = df[df['sex'] == 2]

# b. Merge two subsets (male and female)
merged_subsets = pd.concat([male_subset, female_subset], axis=0)

# c. Sort Data using age, SGOT, and protime
# Handle NaN values in sorting columns by filling them with a large value to sort them last
sorted_df = df.sort_values(by=['age', 'sgot', 'protime'],
                          na_position='last',
                          ascending=[True, True, True])

# d. Transposing Data
transposed_df = df.transpose()

# e. Melting Data to long format
melted_df = pd.melt(df, id_vars=['sex'],
                    value_vars=['age', 'sgot', 'protime', 'bilirubin', 'albumin'],
                    var_name='measurement', value_name='value')

# f. Casting data to wide format
wide_df = melted_df.pivot_table(index='sex', columns='measurement', values='value', aggfunc='mean')
wide_df = wide_df.reset_index()

# Print results to verify
print("Male Subset:\n", male_subset.head())
print("Female Subset:\n", female_subset.head())
print("Merged Subsets (Male and Female):\n", merged_subsets.head())
print("Sorted by Age, SGOT, Protime:\n", sorted_df.head())
print("Transposed DataFrame:\n", transposed_df)
print("Melted DataFrame:\n", melted_df.head())
print("Wide Format DataFrame:\n", wide_df)

Male Subset:
 Empty DataFrame
Columns: [age, sex, steroid, antivirals, fatigue, malaise, anorexia, liver_big, liver_firm, spleen_palpable, spiders, ascites, varices, bilirubin, alk_phosphate, sgot, albumin, protime, histology, class]
Index: []
Female Subset:
 Empty DataFrame
Columns: [age, sex, steroid, antivirals, fatigue, malaise, anorexia, liver_big, liver_firm, spleen_palpable, spiders, ascites, varices, bilirubin, alk_phosphate, sgot, albumin, protime, histology, class]
Index: []
Merged Subsets (Male and Female):
 Empty DataFrame
Columns: [age, sex, steroid, antivirals, fatigue, malaise, anorexia, liver_big, liver_firm, spleen_palpable, spiders, ascites, varices, bilirubin, alk_phosphate, sgot, albumin, protime, histology, class]
Index: []
Sorted by Age, SGOT, Protime:
      age     sex steroid  antivirals fatigue malaise anorexia liver_big  \
110    7  female    True       False   False   False    False      True
37    20    male   False       False    True    True     True     False
121   20  female   False       False    True    True     True      True
148   20  female   False       False   False   False    False      True
20    22    male    True        True    True   False    False      True

    liver_firm spleen_palpable spiders ascites varices  bilirubin  \
110       True            True   False   False   False        0.7
37        True            True    True   False   False        2.3
121      False           False    True    True   False        1.0
148        NaN           False   False   False   False        0.9
20       False           False   False   False   False        0.9

     alk_phosphate   sgot  albumin  protime  histology class
110          256.0   25.0      4.2      NaN       True  live
37           150.0   68.0      3.9      NaN      False  live
121          160.0  118.0      2.9     23.0       True  live
148           89.0  152.0      4.0      NaN       True  live
20            48.0   20.0      4.2     64.0      False  live
Transposed DataFrame:
                    0       1       2       3       4       5       6    \
age                 30      50      78      31      34      34      51
sex               male  female  female  female  female  female  female
steroid          False   False    True     NaN    True    True   False
antivirals       False   False   False    True   False   False   False
fatigue          False    True    True   False   False   False    True
malaise          False   False   False   False   False   False   False
anorexia         False   False   False   False   False   False    True
liver_big        False   False    True    True    True    True    True
liver_firm       False   False   False   False   False   False   False
spleen_palpable  False   False   False   False   False   False    True
spiders          False   False   False   False   False   False    True
ascites          False   False   False   False   False   False   False
varices          False   False   False   False   False   False   False
bilirubin          1.0     0.9     0.7     0.7     1.0     0.9     NaN
alk_phosphate     85.0   135.0    96.0    46.0     NaN    95.0     NaN
sgot              18.0    42.0    32.0    52.0   200.0    28.0     NaN
albumin            4.0     3.5     4.0     4.0     4.0     4.0     NaN
protime            NaN     NaN     NaN    80.0     NaN    75.0     NaN
histology        False   False   False   False   False   False   False
class             live    live    live    live    live    live     die

                    7       8       9    ...     145     146     147     148  \
age                  23      39      30  ...      31      41      70      20
sex              female  female  female  ...  female  female  female  female
steroid            True    True    True  ...   False    True   False   False
antivirals        False   False   False  ...   False   False   False   False
fatigue           False    True   False  ...    True    True    True   False
malaise           False   False   False  ...   False   False    True   False
anorexia          False   False   False  ...   False   False    True   False
liver_big          True    True    True  ...    True    True     NaN    True
liver_firm        False    True   False  ...   False    True     NaN     NaN
spleen_palpable   False   False   False  ...   False    True     NaN   False
spiders           False   False   False  ...   False    True     NaN   False
ascites           False   False   False  ...   False   False     NaN   False
varices           False   False   False  ...   False    True     NaN   False
bilirubin           1.0     0.7     1.0  ...     1.2     4.2     1.7     0.9
alk_phosphate       NaN     NaN     NaN  ...    75.0    65.0   109.0    89.0
sgot                NaN    48.0   120.0  ...   173.0   120.0   528.0   152.0
albumin             NaN     4.4     3.9  ...     4.2     3.4     2.8     4.0
protime             NaN     NaN     NaN  ...    54.0     NaN    35.0     NaN
histology         False   False   False  ...    True    True    True    True
class              live    live    live  ...    live     die     die    live

                    149     150     151     152    153     154
age                  36      46      44      61     53      43
sex              female  female  female  female   male  female
steroid            True    True    True   False  False    True
antivirals        False   False   False   False  False   False
fatigue           False    True    True    True   True    True
malaise           False    True   False    True  False   False
anorexia          False    True   False   False  False   False
liver_big          True    True    True   False   True    True
liver_firm        False   False    True    True  False   False
spleen_palpable   False   False   False   False   True    True
spiders           False    True   False    True   True    True
ascites           False    True   False   False  False    True
varices           False    True   False   False   True   False
bilirubin           0.6     7.6     0.9     0.8    1.5     1.2
alk_phosphate     120.0     NaN   126.0    75.0   81.0   100.0
sgot               30.0   242.0   142.0    20.0   19.0    19.0
albumin             4.0     3.3     4.3     4.1    4.1     3.1
protime             NaN    50.0     NaN     NaN   48.0    42.0
histology          True    True    True    True   True    True
class              live     die    live    live   live     die

[20 rows x 155 columns]
Melted DataFrame:
       sex measurement  value
0    male         age   30.0
1  female         age   50.0
2  female         age   78.0
3  female         age   31.0
4  female         age   34.0
Wide Format DataFrame:
 measurement     sex        age   albumin  bilirubin    protime       sgot
0            female  41.165468  3.816000   1.451128  61.948052  86.437037
1              male  41.500000  3.828571   1.231250  61.181818  81.312500